# This is a basic workflow to help you get started with Actions

name: beta

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
      - 'release/**'
      - 'master'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Run a one-line script
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - uses: actions/github-script@v2
      id: get-commit-messages
      with:
        script: |
          var gitContext = ${{ toJson(github) }};
          return gitContext.event.commits.map((v)=> {
            var msg = v.message;
            const lines = msg.split('\n');
            var text = "";
            for(var i = 1; i < lines.length; i++){
              text += lines[i];
            }

            return "- title : " + lines[0] + "\n- message\n" + text + "\n========================================\n\n";
          }).join('\n');
        result-encoding: string
        
    - name: Get result
      run: echo "${{ steps.get-commit-messages.outputs.result }}"

